spring.application.name=mixxed

server.port=7080
remember_me.session_key=${REMEMBER_ME_SESSION_KEY}

spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/${POSTGRES_DB}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${POSTGRES_USER}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${POSTGRES_PASSWORD}}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

minio.endpoint=${MINIO_ENDPOINT:http://localhost:9000}
minio.access-key=${MINIO_ACCESS_KEY:${MINIO_ROOT_USER}}
minio.secret-key=${MINIO_SECRET_KEY:${MINIO_ROOT_PASSWORD}}
minio.bucket=${MINIO_BUCKET_NAME}
spring.config.import=optional:file:.env[.properties]

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false

mixxed.admin.usernames=${ADMIN_USERNAMES}
mixxed.populate.demo.data=${POPULATE_WITH_DEMO_DATA}
